//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogComment
    {
        public BlogComment()
        {
            this.BlogItem = new HashSet<BlogItem>();
        }
    
        public int CommentId { get; set; }
        public int CommentIdBlog { get; set; }
        public string CommentText { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public Nullable<int> KorisnikId { get; set; }
    
        public virtual ICollection<BlogItem> BlogItem { get; set; }
    }
}
